services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    labels:
      - "com.update.depends-on=prometheus"
    ports:
      - "3000:3000"

  pg-admin:
    image: dpage/pgadmin4:7.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    labels:
      - "com.update.depends-on=grafana"
    ports:
      - "8080:80"