services:
  moby-sync:
    image: moby-sync:latest
    container_name: moby-sync
    restart: unless-stopped
    ports:
      - "5080:5080"
    environment:
      API_KEY: "super-secret-key"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock      
      - ~/.docker/config.json:/creds/config.json:ro
      - ./appsettings.json:/app/appsettings.json